---
language: python

python: "3.6"

sudo: required

matrix:
  fast_finish: true

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-apt

install:
  - pip install ansible ansible-lint
  - pip --version
  - python --version
  - ansible --version
  - "printf '[defaults]\nroles_path = ../\nremote_tmp = ./tmp' > ansible.cfg"
  - mkdir -p ./tmp

script:
  - ansible-lint tasks/main.yml
  - ansible-playbook -i tests/inventory --syntax-check --list-tasks tests/test.yml
  - ansible-playbook -i tests/inventory --connection=local --sudo -vvvv tests/test.yml -u root
  - >
    ansible-playbook -i tests/inventory --connection=local --sudo -vvvv tests/test.yml -u root
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)
